server:
  port: 8080
  host: localhost
  servlet:
    context-path: /api


spring:

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/freelancer
    username: postgres
    password: makarona123
    platform: org.hibernate.dialect.PostgreSQLDialect

  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

security:
  oauth2:
    resource:
      filter-order: 3
  signing-key: MaYzkSjmkzPC57L
  encoding-strength: 5
  security-realm: ImaginarySecurityRealm
  jwt:
     client-id: testjwtclientid
     client-secret: secretpasw
     grant-type: password
     scope-read: read
     scope-write: write
     resource-ids: testjwtresourceid
     client-expire-time-millis: 324324
